### ISSUE TITLE
Threading Error when using radical-synapse-emulate

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.synapse#10]
I've been trying to emulate one of Vivek's workflows. I set up an enviornment on Comet with RP and Synapse installed. When I run radical-synapse-emulate, I get the following error

EDIT: I am using the Pypi release versions of RP and Synapse. Virtualenv is 15.0.2, also from Pypi

```
Traceback (most recent call last):
  File "/home/mingtha/bin/virtualenv-15.0.2/ve.timings_comet_compute/bin/radical-synapse-emulate", line 61, in <module>
    emu_source(sys.argv[2])
  File "/home/mingtha/bin/virtualenv-15.0.2/ve.timings_comet_compute/bin/radical-synapse-emulate", line 28, in emu_source
    info, ret, out = rs.emulate (src=src)
  File "/home/mingtha/bin/virtualenv-15.0.2/ve.timings_comet_compute/lib/python2.7/site-packages/radical/synapse/synapse.py", line 325, in emulate
    _emulator (samples)
  File "/home/mingtha/bin/virtualenv-15.0.2/ve.timings_comet_compute/lib/python2.7/site-packages/radical/synapse/synapse.py", line 219, in _emulator
    atoms[_STO] = rsa.Storage ()
  File "/home/mingtha/bin/virtualenv-15.0.2/ve.timings_comet_compute/lib/python2.7/site-packages/radical/synapse/atoms/storage.py", line 28, in __init__
    AtomBase.__init__ (self, STORAGE)
  File "/home/mingtha/bin/virtualenv-15.0.2/ve.timings_comet_compute/lib/python2.7/site-packages/radical/synapse/atoms/base.py", line 56, in __init__
    self._proc.start ()
  File "/opt/python/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

**Comment by andre-merzky** [comment]
Please use the `feature/named_storage` branch of synapse.  The RP version should have no influence on this specific error.

**Comment by mingtaiha** [comment]
I get this even when I used that branch. I should note that it works for Stampede, BW, Gordon, and SuperMIC. Just not Comet

**Comment by andre-merzky** [comment]
Ok, thanks.  Can you send me the command line you use?  I'll try to reproduce that on comet.

**Comment by mingtaiha** [comment]
It's just `radical-synapse-emulate -i 84.json`, where `84.json` is one of [Vivek's profiles](https://github.com/radical-experiments/AIMES-Swift/tree/master/viveks_workflow/profiles)

**Comment by andre-merzky** [comment]
Great, thanks.

**Comment by andre-merzky** [comment]
I think this is a limitation on the comet head node -- you should be able to run things on the compute nodes.  But, unless you do skeleton experiments, please revert to the devel or master branch of synapse.

You can use

```
srun -N 1 -t 600 --pty bash
```

to get interactive access to a Comet node for 10 min, which simplifies testing.  Let me know how it goes!

**Comment by mingtaiha** [comment]
My bad, I should have mentioned that I encountered this error after I requested an interactive node. I used qsub rather than srun, but I don't think that should matter. Here's the command for requesting

`qsub -I -q compute -l nodes=1:ppn=24:native,walltime=04:00:00 -A TG-CCR140028`

EDIT: I tried it your way and it works now. I think it's because qsub is SGE but srun is SLURM, and I was using commands associated with the incorrect LRMS (using SGE instead of SLURM).

**Comment by andre-merzky** [comment]
Hmm, then I am afraid I can't reproduce this -- I had the exact same error on the head node, but did run the same command successfully on the compute node.  Let me retry with qsub -- that should indeed make no difference, but, who knows...

**Comment by andre-merzky** [comment]
WTF -- it works on a compute node with srun, but fails under qsub.  Bummer!

I'll be going to open a ticket I think, I am quite confused at this point...

**Comment by marksantcroos** [comment]
> Let me retry with qsub -- that should indeed make no difference, but, who knows...

Its not unlikely the environment will be different for the two.

**Comment by andre-merzky** [comment]
Well, as embarassing as it is, the problem was that, unlike srun, the `qsub -I` call does not result in a shell on the target node, but just an allocation -- after ssh to the compute node, all seems to work well...

**Comment by marksantcroos** [comment]
Its a SLURM installation, so qsub is probably some wrapper around salloc.

**Comment by andre-merzky** [comment]
Yep, probably true
