### ISSUE TITLE
Question about Compute Atom

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.synapse#17]
Hey @andre-merzky, I've going through the code to get a better understanding of how the Compute Atom works. I followed the code down the the assembly code. I was wondering why is there a `0.6` factor in [`_verify`](https://github.com/radical-cybertools/radical.synapse/blob/devel/src/radical/synapse/atoms/compute.py#L31)

**Comment by andre-merzky** [comment]
Short answer: our assembly loop does not consume an exact MFLOP, but rather `10/6`th of a MFLOP, and this factor (`6/10`)corrects for that.   

Longer answer: while the assembly code *should* consume something in the ballpark of an MFLOP, there are two problems: 

* MFLOP is ill defined, specifically for multiscalar processors, both while profiling and emulating.
* the measure is highly dependent on code efficiency

I found that the factor 0.6 results in  approximately the same *time* being used when emulating 1MFLOP with synapse, compared to measured MFLOP numbers in some applications (that seems true for several different applications, on different machines).   I am not sure if this corrects definition, profiling, or emulation - but it also does not matter.

For all practical purposes, this means that our MFLOP numbers are not directly comparable to MFLOP numbers obtained by other profilers - but I found little consistency between other profilers, too, in that context, tbh.

Does that help?

**Comment by mingtaiha** [comment]
Ah I see. I thought it would be possible to approximately calculate the number of cycles needed to run the Synapse emulation. I'll probably have more questions regarding this, but I'll close this ticket for now and re-open it if I have more questions.

Thanks!

**Comment by andre-merzky** [comment]
Yeah, one would think that the loop in https://github.com/radical-cybertools/radical.synapse/blob/devel/src/radical/synapse/atoms/synapse_compute_asm.c#L105 has a straight-forward FLOP count: 4 store/move ops, 4 mult, 3 add (one for the i++), and a shift / if (in the loop condition check).  Alas, when profiling that is not really what I got as counters at the end... :/  Happy to hear your thoughts / results on this!
